=== ClanTri/BX-for-binary-file/100/postgres_users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://example.org/users"
           xmlns="http://example.org/users"
           elementFormDefault="qualified">
  <xs:simpleType name="Gender">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Male"/>
      <xs:enumeration value="Female"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="users">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="user" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="xs:int"/>
              <xs:element name="name">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="32"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="gender" type="Gender"/>
              <xs:element name="age" type="xs:int"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ClanTri/BX-for-binary-file/1000/postgres_users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns="http://example.org/users"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://example.org/users postgres_users.xsd">
  <user>
    <id>601</id>
    <name>Eve</name>
    <gender>Female</gender>
    <age>40</age>
  </user>
  <user>
    <id>602</id>
    <name>Hua</name>
    <gender>Female</gender>
    <age>37</age>
  </user>
  <user>
    <id>603</id>
    <name>Sota</name>
    <gender>Male</gender>
    <age>29</age>
  </user>
  <user>
    <id>604</id>
    <name>Itsuki</name>
    <gender>Female</gender>
    <age>35</age>
  </user>
  <user>
    <id>605</id>
    <name>Itsuki</name>
    <gender>Female</gender>
    <age>38</age>
  </user>
  <user>
    <id>606</id>
    <name>Alice</name>
    <gender>Male</gender>
    <age>19</age>
  </user>
  <user>
    <id>607</id>
    <name>Niaj</name>
    <gender>Female</gender>
    <age>52</age>
  </user>
  <user>
    <id>608</id>
    <name>Mallory</name>
    <gender>Female</gender>
    <age>32</age>
  </user>
  <user>
    <id>609</id>
    <name>Aoi</name>
    <gender>Male</gender>
    <age>50</age>
  </user>
  <user>
    <id>610</id>
    <name>Sun Lei</name>
    <gender>Female</gender>
    <age>35</age>
  </user>
  <user>
    <id>611</id>
    <name>Takumi</name>
    <gender>Female</gender>
    <age>49</age>
  </user>
  <user>
    <id>612</id>
    <name>Hina</name>
    <gender>Female</gender>
    <age>54</age>
  </user>
  <user>
    <id>613</id>
    <name>Li Hua</name>
    <gender>Female</gender>
    <age>18</age>
  </user>
  <user>
    <id>614</id>
    <name>Ivan</name>
    <gender>Female</gender>
    <age>27</age>
  </user>
  <user>
    <id>615</id>
    <name>Grace</name>
    <gender>Male</gender>
    <age>29</age>
  </user>
  <user>
    <id>616</id>
    <name>Aoi</name>
    <gender>Female</gender>
    <age>52</age>
  </user>
  <user>
    <id>617</id>
    <name>Grace</name>
    <gender>Male</gender>
    <age>35</age>
  </user>
  <user>
    <id>618</id>
    <name>Alice</name>
    <gender>Female</gender>
    <age>26</age>
  </user>
  <user>
    <id>619</id>
    <name>Hua</name>
    <gender>Male</gender>
    <age>46</age>
  </user>
  <user>
    <id>620</id>
    <name>Sota</name>
    <gender>Male</gender>
    <age>53</age>
  </user>
  <user>
    <id>621</id>
    <name>Wei</name>
    <gender>Female</gender>
    <age>56</age>
  </user>
  <user>
    <id>622</id>
    <name>Itsuki</name>
    <gender>Female</gender>
    <age>25</age>
  </user>
  <user>
    <id>623</id>
    <name>Zhao Min</name>
    <gender>Female</gender>
    <age>30</age>
  </user>
  <user>
    <id>624</id>
    <name>Bob</name>
    <gender>Female</gender>
    <age>20</age>
  </user>
  <user>
    <id>625</id>
    <name>Liu Yang</name>
    <gender>Male</gender>
    <age>29</age>
  </user>
  <user>
    <id>626</id>
    <name>Peggy</name>
    <gender>Male</gender>
    <age>54</age>
  </user>
  <user>
    <id>627</id>
    <name>Takumi</name>
    <gender>Male</gender>
    <age>40</age>
  </user>
  <user>
    <id>628</id>
    <name>Itsuki</name>
    <gender>Male</gender>
    <age>35</age>
  </user>
  <user>
    <id>629</id>
    <name>Yvonne</name>
    <gender>Male</gender>
    <age>27</age>
  </user>
  <user>
    <id>630</id>
    <name>Hua</name>
    <gender>Male</gender>
    <age>29</age>
  </user>
  <user>
    <id>631</id>
    <name>Peggy</name>
    <gender>Male</gender>
    <age>19</age>
  </user>
  <user>
    <id>632</id>
    <name>Chen Jie</name>
    <gender>Female</gender>
    <age>43</age>
  </user>
  <user>
    <id>633</id>
    <name>Hina</name>
    <gender>Female</gender>
    <age>55</age>
  </user>
  <user>
    <id>634</id>
    <name>Zhao Min</name>
    <gender>Female</gender>
    <age>44</age>
  </user>
  <user>
    <id>635</id>
    <name>Li Hua</name>
    <gender>Male</gender>
    <age>23</age>
  </user>
  <user>
    <id>636</id>
    <name>Takumi</name>
    <gender>Female</gender>
    <age>25</age>
  </user>
  <user>
    <id>637</id>
    <name>Heidi</name>
    <gender>Male</gender>
    <age>23</age>
  </user>
  <user>
    <id>638</id>
    <name>Wendy</name>
    <gender>Male</gender>
    <age>33</age>
  </user>
  <user>
    <id>639</id>
    <name>Aoi</name>
    <gender>Female</gender>
    <age>49</age>
  </user>
  <user>
    <id>640</id>
    <name>Sybil</name>
    <gender>Female</gender>
    <age>25</age>
  </user>
  <user>
    <id>641</id>
    <name>Olivia</name>
    <gender>Female</gender>
    <age>35</age>
  </user>
  <user>
    <id>642</id>
    <name>Heidi</name>
    <gender>Male</gender>
    <age>24</age>
  </user>
  <user>
    <id>643</id>
    <name>Judy</name>
    <gender>Female</gender>
    <age>39</age>
  </user>
  <user>
    <id>644</id>
    <name>Yui</name>
    <gender>Female</gender>
    <age>22</age>
  </user>
  <user>
    <id>645</id>
    <name>Sun Lei</name>
    <gender>Male</gender>
    <age>18</age>
  </user>
  <user>
    <id>646</id>
    <name>Sun Lei</name>
    <gender>Male</gender>
    <age>31</age>
  </user>
  <user>
    <id>647</id>
    <name>Haruto</name>
    <gender>Male</gender>
    <age>42</age>
  </user>
  <user>
    <id>648</id>
    <name>Wang Fang</name>
    <gender>Female</gender>
    <age>55</age>
  </user>
  <user>
    <id>649</id>
    <name>Niaj</name>
    <gender>Female</gender>
    <age>28</age>
  </user>
  <user>
    <id>650</id>
    <name>Chen Jie</name>
    <gender>Male</gender>
    <age>40</age>
  </user>
  <user>
    <id>651</id>
    <name>Ivan</name>
    <gender>Female</gender>
    <age>27</age>
  </user>
  <user>
    <id>652</id>
    <name>Grace</name>
    <gender>Male</gender>
    <age>41</age>
  </user>
  <user>
    <id>653</id>
    <name>Heidi</name>
    <gender>Female</gender>
    <age>36</age>
  </user>
  <user>
    <id>654</id>
    <name>Rupert</name>
    <gender>Female</gender>
    <age>19</age>
  </user>
  <user>
    <id>655</id>
    <name>Eve</name>
    <gender>Female</gender>
    <age>34</age>
  </user>
  <user>
    <id>656</id>
    <name>Haruto</name>
    <gender>Female</gender>
    <age>40</age>
  </user>
  <user>
    <id>657</id>
    <name>Wendy</name>
    <gender>Female</gender>
    <age>43</age>
  </user>
  <user>
    <id>658</id>
    <name>Niaj</name>
    <gender>Female</gender>
    <age>42</age>
  </user>
  <user>
    <id>659</id>
    <name>Frank</name>
    <gender>Male</gender>
    <age>25</age>
  </user>
  <user>
    <id>660</id>
    <name>Haruto</name>
    <gender>Male</gender>
    <age>53</age>
  </user>
  <user>
    <id>661</id>
    <name>Heidi</name>
    <gender>Female</gender>
    <age>37</age>
  </user>
  <user>
    <id>662</id>
    <name>Wendy</name>
    <gender>Female</gender>
    <age>49</age>
  </user>
  <user>
    <id>663</id>
    <name>Sun Lei</name>
    <gender>Male</gender>
    <age>17</age>
  </user>
  <user>
    <id>664</id>
    <name>Yvonne</name>
    <gender>Male</gender>
    <age>17</age>
  </user>
  <user>
    <id>665</id>
    <name>Sakura</name>
    <gender>Male</gender>
    <age>41</age>
  </user>
  <user>
    <id>666</id>
    <name>Ming</name>
    <gender>Female</gender>
    <age>30</age>
  </user>
  <user>
    <id>667</id>
    <name>Yvonne</name>
    <gender>Male</gender>
    <age>48</age>
  </user>
  <user>
    <id>668</id>
    <name>Olivia</name>
    <gender>Female</gender>
    <age>29</age>
  </user>
  <user>
    <id>669</id>
    <name>Haruto</name>
    <gender>Female</gender>
    <age>19</age>
  </user>
  <user>
    <id>670</id>
    <name>Wei</name>
    <gender>Male</gender>
    <age>17</age>
  </user>
  <user>
    <id>671</id>
    <name>Alice</name>
    <gender>Male</gender>
    <age>47</age>
  </user>
  <user>
    <id>672</id>
    <name>Li Hua</name>
    <gender>Female</gender>
    <age>56</age>
  </user>
  <user>
    <id>673</id>
    <name>Yvonne</name>
    <gender>Male</gender>
    <age>35</age>
  </user>
  <user>
    <id>674</id>
    <name>Wei</name>
    <gender>Male</gender>
    <age>51</age>
  </user>
  <user>
    <id>675</id>
    <name>Aoi</name>
    <gender>Male</gender>
    <age>38</age>
  </user>
  <user>
    <id>676</id>
    <name>Wendy</name>
    <gender>Female</gender>
    <age>20</age>
  </user>
  <user>
    <id>677</id>
    <name>Wang Fang</name>
    <gender>Female</gender>
    <age>31</age>
  </user>
  <user>
    <id>678</id>
    <name>Carol</name>
    <gender>Male</gender>
    <age>19</age>
  </user>
  <user>
    <id>679</id>
    <name>Haruto</name>
    <gender>Male</gender>
    <age>23</age>
  </user>
  <user>
    <id>680</id>
    <name>Haruto</name>
    <gender>Male</gender>
    <age>36</age>
  </user>
  <user>
    <id>681</id>
    <name>Sakura</name>
    <gender>Male</gender>
    <age>23</age>
  </user>
  <user>
    <id>682</id>
    <name>Yvonne</name>
    <gender>Female</gender>
    <age>22</age>
  </user>
  <user>
    <id>683</id>
    <name>Aoi</name>
    <gender>Male</gender>
    <age>25</age>
  </user>
  <user>
    <id>684</id>
    <name>Yui</name>
    <gender>Male</gender>
    <age>24</age>
  </user>
  <user>
    <id>685</id>
    <name>Sybil</name>
    <gender>Female</gender>
    <age>51</age>
  </user>
  <user>
    <id>686</id>
    <name>Alice</name>
    <gender>Male</gender>
    <age>22</age>
  </user>
  <user>
    <id>687</id>
    <name>Wei</name>
    <gender>Female</gender>
    <age>46</age>
  </user>
  <user>
    <id>688</id>
    <name>Yvonne</name>
    <gender>Male</gender>
    <age>20</age>
  </user>
  <user>
    <id>689</id>
    <name>Sun Lei</name>
    <gender>Male</gender>
    <age>50</age>
  </user>
  <user>
    <id>690</id>
    <name>Hina</name>
    <gender>Male</gender>
    <age>24</age>
  </user>
  <user>
    <id>691</id>
    <name>Yui</name>
    <gender>Female</gender>
    <age>36</age>
  </user>
  <user>
    <id>692</id>
    <name>Itsuki</name>
    <gender>Female</gender>
    <age>47</age>
  </user>
  <user>
    <id>693</id>
    <name>Wei</name>
    <gender>Male</gender>
    <age>38</age>
  </user>
  <user>
    <id>694</id>
    <name>Alice</name>
    <gender>Female</gender>
    <age>40</age>
